package com.solisium.core.query

import com.solisium.core.domain.ProgressionCadence
import com.solisium.core.domain.ProgressionDifficulty
import com.solisium.core.domain.ProgressionEase
import com.solisium.core.domain.ProgressionTaskTemplate

/** Curated progression tasks until warehouse contract/codex tables are collected. */
object ProgressionCatalog {
    val templates: List<ProgressionTaskTemplate> = listOf(
        ProgressionTaskTemplate(
            id = "daily_contracts",
            title = "Daily contracts",
            detail = "Turn in or progress daily contract slots on the commission board.",
            cadence = ProgressionCadence.Daily,
            category = "Contracts",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 85,
        ),
        ProgressionTaskTemplate(
            id = "daily_codex",
            title = "Adventure codex dailies",
            detail = "Knock out codex objectives that reset daily — quick progression when they match your zone.",
            cadence = ProgressionCadence.Daily,
            category = "Codex",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 80,
        ),
        ProgressionTaskTemplate(
            id = "daily_dynamic",
            title = "Dynamic event window",
            detail = "Join the current 3-hour dynamic rotation for XP, tokens, and weekly-style progress.",
            cadence = ProgressionCadence.Daily,
            category = "Events",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 75,
        ),
        ProgressionTaskTemplate(
            id = "daily_materials",
            title = "Material dailies / crafting orders",
            detail = "Spend gathered mats on dailies that feed gear score or weapon progression.",
            cadence = ProgressionCadence.Daily,
            category = "Crafting",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 60,
        ),
        ProgressionTaskTemplate(
            id = "weekly_contracts",
            title = "Weekly contracts",
            detail = "Higher-value contract track — prioritize before reset if tokens or gear are gated.",
            cadence = ProgressionCadence.Weekly,
            category = "Contracts",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 90,
        ),
        ProgressionTaskTemplate(
            id = "weekly_boss",
            title = "Field / world boss windows",
            detail = "19:00 and 22:00 server windows plus any weekly boss objectives you track.",
            cadence = ProgressionCadence.Weekly,
            category = "Bosses",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Heavy,
            progressionValue = 88,
            minLevel = 40,
        ),
        ProgressionTaskTemplate(
            id = "weekly_codex",
            title = "Weekly codex chapters",
            detail = "Finish or advance codex lines that only move once per week.",
            cadence = ProgressionCadence.Weekly,
            category = "Codex",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 82,
        ),
        ProgressionTaskTemplate(
            id = "monthly_season",
            title = "Season / monthly track",
            detail = "Season pass, monthly shop caps, or long-window objectives before they expire.",
            cadence = ProgressionCadence.Monthly,
            category = "Season",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 70,
        ),
        ProgressionTaskTemplate(
            id = "always_mastery",
            title = "Weapon mastery grind",
            detail = "Push mastery levels on your main weapons — typed on Character, not auto-read from the client.",
            cadence = ProgressionCadence.Always,
            category = "Mastery",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 78,
        ),
        ProgressionTaskTemplate(
            id = "always_skill_cores",
            title = "Skill cores & influences",
            detail = "Fill empty skill-core and influence slots on the skills screen.",
            cadence = ProgressionCadence.Always,
            category = "Build layers",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 86,
        ),
        ProgressionTaskTemplate(
            id = "always_gear",
            title = "Gear upgrades from build plan",
            detail = "Replace weak slots using Build recommendations — warehouse-ranked, not live DPS.",
            cadence = ProgressionCadence.Always,
            category = "Gear",
            baseEase = ProgressionEase.Moderate,
            difficulty = ProgressionDifficulty.Standard,
            progressionValue = 92,
        ),
        ProgressionTaskTemplate(
            id = "always_tokens",
            title = "Spend progression tokens",
            detail = "Contract coins, resistance tokens, and similar currencies before capping.",
            cadence = ProgressionCadence.Always,
            category = "Tokens",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 65,
        ),
        ProgressionTaskTemplate(
            id = "nix_talking_wall",
            title = "Talking Wall (Nix)",
            detail = "Trivia window in Nix — use the Wall tab when a statement pops. Track drop watermark on Build (~3h17 cadence).",
            cadence = ProgressionCadence.Always,
            category = "Events",
            baseEase = ProgressionEase.Easy,
            difficulty = ProgressionDifficulty.Light,
            progressionValue = 55,
            minLevel = 55,
            tokenTags = setOf("nix"),
        ),
    )

    fun byId(id: String): ProgressionTaskTemplate? = templates.firstOrNull { it.id == id }
}
